version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        env_file:
            - .env
        environment:
            - DB_HOST=postgres
            - DB_USERNAME=mahmudul
            - DB_PASSWORD=152155809
            - DB_NAME=typescript_express_starter
        volumes:
            - ./src:/app/src
        user: "1000:1000"
        command: npm run dev
        depends_on:
            - redis
            - postgres

    redis:
        image: redis:6-alpine
        ports:
            - "6380:6379"
        environment:
            - REDIS_PASSWORD=foobared
        command: ["redis-server", "--requirepass", "foobared"]
        volumes:
            - redis-data:/data

    postgres:
        image: postgres:14-alpine
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: typescript_express_starter
            POSTGRES_USER: mahmudul
            POSTGRES_PASSWORD: 152155809
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    redis-data:
    postgres-data:
